New attempt
MarekWadinger/dynamic_opt_growth_model pull request #5
Opened 2024-01-30 13:39 UTC by rfaber1

2024-01-31 02:30 UTC, MarekWadinger requested changes
Please address the issues raised in comments on respective changes

2024-01-31 02:30 UTC, MarekWadinger commented on .idea/.gitignore
Please add .idea folder to .gitignore and remove the files from cache.

2024-01-31 02:30 UTC, MarekWadinger commented on .idea/.gitignore
Please add /.idea folder to .gitignore and remove the cached data.

2024-01-31 02:30 UTC, MarekWadinger commented on GESmodel/CO2.png
Please create a separate folder /results for the output files (.png, .txt, ...)

2024-01-31 02:30 UTC, MarekWadinger commented on GESmodel/modelFcn.py
Please, remove this if not used.

2024-01-31 02:30 UTC, MarekWadinger commented on GESmodel/simpleModel.py
In general, if the state is not used (increment zeroed out in return) it should not be used in the input to the model. If the state is required for computation of other states, than it must be returned if evolves in time. If no evolution is expected, consider converting state to constant.

2024-01-31 02:30 UTC, MarekWadinger commented on GESmodel/simpleParameters.py
Isn't this a duplicate of core/simpleParameters.py ?

2024-01-31 02:30 UTC, MarekWadinger commented on core/greenhouse_model.py
Please remove non-informative comments

2024-01-31 04:49 UTC, MarekWadinger commented
@rfaber1  Please revise my proposed changes

2024-02-05 10:32 UTC, rfaber1 reviewed
ok

2024-02-10 06:15 UTC, MarekWadinger approved these changes

2024-02-10 06:16 UTC, merged